# Generated by Django 3.2 on 2021-06-03 10:17
import os
from django.db import migrations


def make_admin_if_necessary(apps, schema_editor):
    User = apps.get_model("auth", "User")
    pw = os.environ.get(
        'DEFAULT_ENCRYPTED_PASSWORD', 'pbkdf2_sha256$30000$HYBf8GKHBrP8$FqGUTXGpolLinnpBFAQmecN+XorRSLzvBUNqconDLzU=')
    if not User.objects.all().exists():
        admin = User.objects.create(username='admin', is_superuser=True, is_staff=True, password=pw)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(make_admin_if_necessary)
    ]
